variables:
  REGISTRY_BASE: registry.gitlab.com/baixingwang/devops-user-service
  IMAGE_REF: $REGISTRY_BASE:$CI_PIPELINE_ID

stages:
  - compile
  - test
  - package
  - build
  - deploy

compile:
  stage: compile
  image: maven:3.6.3-adoptopenjdk-11
  only:
    - dev@baixingwang/devops-user-service
  script:
    - export MAVEN_OPTS=-Dmaven.repo.local=$PWD/.m2/repository
    - mvn -U compile
  cache:
    paths:
      - .m2

uni test:
  stage: test
  image: maven:3.6.3-adoptopenjdk-11
  only:
    - dev@baixingwang/devops-user-service
  script:
    - export MAVEN_OPTS=-Dmaven.repo.local=$PWD/.m2/repository
    - mvn clean test && cat target/site/jacoco/index.html
  cache:
    paths:
      - .m2

sonar:
  image: registry.gitlab.baixing.cn/arch/base-images/maven-with-sonar:v0.1
  stage: test
  only:
    - dev@baixingwang/devops-user-service
  script:
    - export SONAR_USER_HOME=$PWD/.sonar
    - mvn clean install sonar:sonar
      -Dsonar.projectKey=devops-user-service
      -Dsonar.dynamicAnalysis=reuseReports
#      -Dsonar.jacoco.reportMissing.force.zero=true
#      -Dsonar.jacoco.reportPaths=$PWD/trade-api/target/jacoco.exec,$PWD/trade-common/target/jacoco.exec,$PWD/trade-model/target/jacoco.exec,$PWD/trade-persistence/target/jacoco.exec,$PWD/trade-service/target/jacoco.exec,$PWD/trade-web/target/jacoco.exec
#      -Dsonar.coverage.exclusions=src/main/java/com/baixing/ms/trade/service/utils/mq/**/*,src/main/java/com/baixing/ms/trade/service/internal/impl/TradeRepoServiceImpl.java,src/main/java/com/baixing/ms/trade/service/v2/trade/impl/TradeRepositoryImpl.java,src/main/java/com/baixing/ms/trade/service/v2/ObjectUtilsV2.java,src/main/java/com/baixing/ms/trade/common/model/**/*,src/main/java/com/baixing/ms/trade/service/recovery/**/*
#      -Dsonar.exclusions=src/main/java/com/baixing/ms/trade/service/coupon/impl/thrift/**/*,src/main/java/com/baixing/ms/trade/service/performance/impl/thrift/**/*
  artifacts:
    expire_in: 1 week
    paths:
      - trade-web/target/*.jar
  cache:
    paths:
      - .m2



maven package:
  stage: package
  image: maven:3.6.3-adoptopenjdk-11
  only:
    - dev@baixingwang/devops-user-service
  script:
    - export MAVEN_OPTS=-Dmaven.repo.local=$PWD/.m2/repository
    - mvn -U package
  artifacts:
    paths:
      - target/app.jar
    expire_in: 12h
  cache:
    paths:
      - .m2

docker build:
  stage: build
  image: docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $IMAGE_REF .
    - docker push $IMAGE_REF
    - docker rmi $IMAGE_REF
  only:
    - dev@baixingwang/devops-user-service
  tags:
    - baixingwang

deploy to dev:
  stage: deploy
  image:
    name: bitnami/kubectl:1.14
    entrypoint: [""]
  script: kubectl set image deployment/dev-devops-user-service devops-user-service=$IMAGE_REF
  environment:
    name: dev
    url: http://dev-devops.baixing.cn:8088/
