stages:
  - maven-build
  - maven-test

maven-build:
  stage: maven-build
  image: maven:3.6.3-adoptopenjdk-11
  only:
    - master@baixingwang/devops-user-service
  script:
    - export MAVEN_OPTS=-Dmaven.repo.local=$PWD/.m2/repository
    - mvn -U compile
  cache:
    paths:
      - .m2

maven-test:
  stage: maven-test
  image: maven:3.6.3-adoptopenjdk-11
  only:
    - master@baixingwang/devops-user-service
  script:
    - export MAVEN_OPTS=-Dmaven.repo.local=$PWD/.m2/repository
    - mvn clean test && cat target/site/jacoco/index.html
  cache:
    paths:
      - .m2
