variables:
  REGISTRY_BASE: registry.gitlab.com/baixingwang/devops-user-service
  IMAGE_REF: $REGISTRY_BASE:$CI_PIPELINE_ID

stages:
  - compile
  - test
  - package
  - build
  - deploy

compile:
  stage: compile
  image: maven:3.6.3-adoptopenjdk-11
  only:
    - dev@baixingwang/devops-user-service
  script:
    - export MAVEN_OPTS=-Dmaven.repo.local=$PWD/.m2/repository
    - mvn -U compile
    - VERSION=$(mvn --non-recursive help:evaluate -Dexpression=project.version | grep -v '\[.*')
    - echo $VERSION
  cache:
    paths:
      - .m2

uni-test:
  stage: test
  image: maven:3.6.3-adoptopenjdk-11
  only:
    - dev@baixingwang/devops-user-service
    - test@baixingwang/devops-user-service
    - master@baixingwang/devops-user-service
    - stg@baixingwang/devops-user-service
  script:
    - export MAVEN_OPTS=-Dmaven.repo.local=$PWD/.m2/repository
    - mvn clean test && cat target/site/jacoco/index.html
  cache:
    paths:
      - .m2

sonar:
  image: maven:3.6.3-adoptopenjdk-11
  stage: test
  only:
    - dev@baixingwang/devops-user-service
    - test@baixingwang/devops-user-service
    - master@baixingwang/devops-user-service
    - stg@baixingwang/devops-user-service
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar
      -Dsonar.qualitygate.wait=true
      -Dmaven.test.skip=true
      -Dsonar.host.url=http://39.100.144.36
      -Dsonar.projectKey=devops-user-service
      -Dsonar.dynamicAnalysis=reuseReports
      -Dsonar.jacoco.reportMissing.force.zero=true
      -Dsonar.jacoco.reportPaths=$PWD/devops-user-service/coverage-reports/jacoco.exec
  allow_failure: true
  dependencies:
    - uni-test

maven package:
  stage: package
  image: maven:3.6.3-adoptopenjdk-11
  only:
    - dev@baixingwang/devops-user-service
  script:
    - export MAVEN_OPTS=-Dmaven.repo.local=$PWD/.m2/repository
    - mvn -U package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/app.jar
    expire_in: 12h
  cache:
    paths:
      - .m2

build:
  stage: build
  image: docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $IMAGE_REF .
    - docker push $IMAGE_REF
    - docker rmi $IMAGE_REF
  only:
    - dev@baixingwang/devops-user-service
  tags:
    - baixingwang

deploy to dev:
  stage: deploy
  image:
    name: bitnami/kubectl:1.14
    entrypoint: [""]
  script: kubectl set image deployment/dev-devops-user-service devops-user-service=$IMAGE_REF
  only:
    - dev@baixingwang/devops-user-service
  environment:
    name: dev
    url: http://dev-devops.baixing.cn:8088

deploy to test:
  stage: deploy
  image:
    name: bitnami/kubectl:1.14
    entrypoint: [""]
  script: kubectl set image deployment/test-devops-user-service devops-user-service=$IMAGE_REF
  only:
    - test@baixingwang/devops-user-service
  environment:
    name: test
    url: http://test-devops.baixing.cn:8088

deploy to stg:
  stage: deploy
  image:
    name: bitnami/kubectl:1.14
    entrypoint: [""]
  script: kubectl set image deployment/stg-devops-user-service devops-user-service=$IMAGE_REF
  only:
    - release@baixingwang/devops-user-service
  environment:
    name: stg
    url: http://stg-devops.baixing.cn:8088

deploy to prod:
  stage: deploy
  image:
    name: bitnami/kubectl:1.14
    entrypoint: [""]
  script: kubectl set image deployment/prod-devops-user-service devops-user-service=$IMAGE_REF
  only:
    - prod@baixingwang/devops-user-service
  environment:
    name: prod
    url: http://prod-devops.baixing.cn:8088/
