variables:
  REGISTRY_BASE: registry.gitlab.com/baixingwang/devops-user-service
  IMAGE_REF: $REGISTRY_BASE:$CI_PIPELINE_ID

stages:
  - compile
  - test
  - package
  - deploy-dev

compile:
  stage: compile
  image: maven:3.6.3-adoptopenjdk-11
  only:
    - dev@baixingwang/devops-user-service
  script:
    - export MAVEN_OPTS=-Dmaven.repo.local=$PWD/.m2/repository
    - mvn -U compile
  cache:
    paths:
      - .m2

uni-test:
  stage: test
  image: maven:3.6.3-adoptopenjdk-11
  only:
    - dev@baixingwang/devops-user-service
  script:
    - export MAVEN_OPTS=-Dmaven.repo.local=$PWD/.m2/repository
    - mvn clean test && cat target/site/jacoco/index.html
  cache:
    paths:
      - .m2

maven-package:
  stage: package
  image: maven:3.6.3-adoptopenjdk-11
  only:
    - dev@baixingwang/devops-user-service
  script:
    - export MAVEN_OPTS=-Dmaven.repo.local=$PWD/.m2/repository
    - mvn -U package
  artifacts:
    paths:
      - target/app.jar
    expire_in: 12h
  cache:
    paths:
      - .m2

image-package:
  stage: package
  image: docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $IMAGE_REF .
    - docker push $IMAGE_REF
    - docker rmi $IMAGE_REF
  only:
    - dev@baixingwang/devops-user-service
  tags:
    - baixingwang

deploy-dev:
  stage: deploy-dev
  image:
    name: bitnami/kubectl:1.14
    entrypoint: [""]
  script: kubectl set image deployment/devops-user-service devops-user-service=$IMAGE_REF
  environment:
    name: dev
    url: https://staging.example.com/
