spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:~/test
    platform: h2
    driverClassName: org.h2.Driver
    schema: classpath:db/init.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
  application:
    name: devops-user-service
  freemarker:
    template-loader-path: classpath:/templates/
    request-context-attribute: request
    charset: UTF-8


management:
  endpoint:
    health:
      show-details: always
    refresh:
      enabled: true
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics, info, prometheus
  health:
    probes:
      enabled: true


---
spring:
  profiles: local
